name: core
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.12.2
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  firebase_auth: ^6.5.6
  firebase_core: ^4.12.1
  flutter:
    sdk: flutter
  cloud_firestore: ^6.7.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
